version: '3.8'

services:
  app:
    image: my-python-app
    build:
      context: ./backend   # 指定正確的 build 目錄
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "app.py"]