version: '3.8'

services:
  app:
    image: my-python-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "app.py"]